spring.application.name=portfolio-service
server.port=8088
spring.profiles.active=reactive

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

spring.cloud.function.definition=handleTrade;handleOrderCreated;handleOrderRejected

#spring.cloud.stream.bindings.handleOrderCreated-in-0.destination=order.events
#spring.cloud.stream.rabbit.bindings.handleOrderCreated-in-0.consumer.binding-routing-key=order.created
#spring.cloud.stream.bindings.handleOrderCreated-in-0.group=portfolio-created-queue
#spring.cloud.stream.bindings.handleOrderCreated-in-0.content-type=application/json
#
#spring.cloud.stream.bindings.handleOrderRejected-in-0.destination=order.events
#spring.cloud.stream.rabbit.bindings.handleOrderRejected-in-0.consumer.binding-routing-key=order.rejected
#spring.cloud.stream.bindings.handleOrderRejected-in-0.group=portfolio-rejected-queue
#spring.cloud.stream.bindings.handleOrderRejected-in-0.content-type=application/json
#
#
#spring.cloud.stream.bindings.handleOrderCreated-out-0.destination=portfolio.events
#spring.cloud.stream.rabbit.bindings.handleOrderCreated-out-0.producer.routingKeyExpression=headers['eventType']
#
#spring.cloud.stream.bindings.handleTrade-in-0.destination=trade.events
#spring.cloud.stream.rabbit.bindings.handleTrade-in-0.consumer.binding-routing-key=trade.executed
#spring.cloud.stream.bindings.handleTrade-in-0.group=portfolio-service-queue


#kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.cloud.stream.bindings.handleOrderCreated-in-0.destination=order.events
spring.cloud.stream.bindings.handleOrderCreated-in-0.group=portfolio-created-group
spring.cloud.stream.bindings.handleOrderCreated-in-0.content-type=application/json

spring.cloud.stream.bindings.handleOrderRejected-in-0.destination=order.events
spring.cloud.stream.bindings.handleOrderRejected-in-0.group=portfolio-rejected-group
spring.cloud.stream.bindings.handleOrderRejected-in-0.content-type=application/json

spring.cloud.stream.bindings.handleOrderCreated-out-0.destination=portfolio.events

spring.cloud.stream.bindings.handleTrade-in-0.destination=trade.events
spring.cloud.stream.bindings.handleTrade-in-0.group=portfolio-trade-group

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:app.pub