spring.application.name=portfolio-service
server.port=8088
spring.profiles.active=reactive

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

spring.cloud.function.definition=handleTrade

spring.cloud.stream.bindings.handleTrade-in-0.destination=orchestration.trades.executed
spring.cloud.stream.bindings.handleTrade-in-0.group=portfolio-service-queue

#kafka
#spring.kafka.bootstrap-servers=localhost:9092
#spring.cloud.stream.bindings.handleTrade-in-0.group=portfolio-service-group
#spring.cloud.stream.kafka.bindings.handleTrade-in-0.consumer.startOffset=latest
#spring.cloud.stream.kafka.bindings.handleTrade-in-0.consumer.resetOffsets=true

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:app.pub