spring.application.name=portfolio-service
server.port=8088
spring.profiles.active=reactive

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit

spring.cloud.function.definition=handleTrade;handleReserveBalance;handleRefund
#
#spring.cloud.stream.bindings.handleReserveBalance-in-0.destination=portfolio.commands
#spring.cloud.stream.bindings.handleReserveBalance-in-0.group=portfolio-queue
#spring.cloud.stream.bindings.handleReserveBalance-in-0.content-type=application/json
#spring.cloud.stream.rabbit.bindings.handleReserveBalance-in-0.consumer.binding-routing-key=portfolio.balance
#
#spring.cloud.stream.bindings.handleReserveBalance-out-0.destination=portfolio.responses
#
#spring.cloud.stream.bindings.handleTrade-in-0.destination=portfolio.commands
#spring.cloud.stream.rabbit.bindings.handleTrade-in-0.consumer.binding-routing-key=portfolio.update
#spring.cloud.stream.bindings.handleTrade-in-0.group=portfolio-trade-queue
#
#
#spring.cloud.stream.bindings.handleRefund-in-0.destination=portfolio.commands
#spring.cloud.stream.rabbit.bindings.handleRefund-in-0.consumer.binding-routing-key=portfolio.refund
#spring.cloud.stream.bindings.handleRefund-in-0.group=portfolio-refund-queue
#

#kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.cloud.stream.bindings.handleReserveBalance-in-0.destination=portfolio.commands
spring.cloud.stream.bindings.handleReserveBalance-in-0.group=portfolio-created-group
spring.cloud.stream.bindings.handleReserveBalance-in-0.content-type=application/json

spring.cloud.stream.bindings.handleReserveBalance-out-0.destination=portfolio.responses

spring.cloud.stream.bindings.handleRefund-in-0.destination=portfolio.commands
spring.cloud.stream.bindings.handleRefund-in-0.group=portfolio-refund-group
spring.cloud.stream.bindings.handleRefund-in-0.content-type=application/json

spring.cloud.stream.bindings.handleOrderCreated-out-0.destination=portfolio.events

spring.cloud.stream.bindings.handleTrade-in-0.destination=portfolio.commands
spring.cloud.stream.bindings.handleTrade-in-0.group=portfolio-trade-group

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:app.pub